sudo: false
notifications:
  email: false
env:
  matrix:
    - LUA="luajit 2.0"
    - LUA="luajit 2.1"
before_install:
  - bash .ci/setup_bcrypt.sh
  - pip install --user hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin
  - luarocks install busted
  - luarocks install luacheck
  - luarocks install luacov-coveralls
install:
  - luarocks make
script:
  -  make lint && busted -v --coverage -o gtest --repeat 3 spec
after_success:
  - luacov-coveralls -i ./src/argon2.lua
cache:
  pip: true